### ISSUE TITLE
cannot find sensor

### ISSUE THREAD

**Issue by himanshu-hearthacker** [duste/FingerprintScannerRaspberryPi#1]
hello duste,
i am using your code to interface finger print sensor,I don't know which sensor you are using but  I have 2 sensors i.e. GT-511c3 and r305 . i tried both of these. but console shows "Unable to find finger print sensor". It would be great if you help where i could be wrong. I tried to change baud rate but No result. I also tried with USB converter but Not yet Successful.

**Comment by duste** [comment]
I am using the R305 (Adafruit 751) with Raspberry pi B+.  The manuals for both of the scanners appear to use the same format.  You should be able to use this code to control ether of the scanners.  There are forums on adafruit site.  If you are using the newer Pi3 model you will need to make sure that you have Python 3, set up the serial port for 57600 baud and AMA0.  
Setting up serial port on B+ user http://www.raspberry-projects.com/pi/pi-operating-systems/raspbian/io-pins-raspbian/uart-pins
Setting up serial port on Pi3 use http://www.briandorey.com/post/Raspberry-Pi-3-UART-Boot-Overlay-Part-Two

This was posted on Adafruit forums from an enthusiast.
This is what I think is the best way to get your fingerprint sensor to work with the RPi:
Reformat SD Card
Install NOOBS
update and ugrade Raspbian
disable serial console
download your code (FPRunTest.py, FPSconstants.py, Fingerprint.py)
Connect the following wires on the fingerprint Sensor to the Raspberry Pi B Plus:
pin 2 - Red (+5V)
pin 6 - Black (Gnd)
pin 8 - White (Tx)
pin 10 - Green (Rx)

run "sudo python3 FPRunTest.py"

**Comment by himanshu-hearthacker** [comment]
Hi Duste,
                Thanks for the response. I tried all the stuff 2-3 times, even on different raspberry pi board,
I also tried with USART GPIO and USB-Serial converter, But got same result every time(Unable to find sensor). My Finger Print Module working  with Adafruit Arduino Finger print library. 
On RPi it gives error something [239],value in rxPacket variable,  when it go for checkFPComms() functions. I don't know where the problem is. I  will try it again. Then get back to you.

**Comment by duste** [comment]
Are you still having the same 239 problem?

**Comment by himanshu-hearthacker** [comment]
Thanks Duste for the Reply. I try with the code but was unsuccessful , but i find another code [https://github.com/girish946/python-R305](url) which i got success in interfacing that. 
To get forward with my project, i will need your help. I want to take have finger enrolment on one system and verification on another system. For that i want to extract finger print  template or image from one module and dump into another module. so that i can verify my finger on another system. Looking forward to hear from you.

**Comment by praveenmalav09** [comment]
How to interface R305 to raspberry pi 3 model B.

**Comment by duste** [comment]
According to Raspberrypi.org the pin configuration is the exact same on B+, 2 and 3 module.

**Comment by praveenmalav09** [comment]
i got this error in FPRunTest.py file. how to resolve this.

Traceback (most recent call last):
  File "FPRunTest.py", line 392, in <module>
    main()
  File "FPRunTest.py", line 326, in main
    Fingerprint.begin()
  File "/home/pi/test/Fingerprint.py", line 43, in begin
    rtscts)
  File "/usr/lib/python2.7/dist-packages/serial/serialutil.py", line 261, in __init__
    self.open()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 278, in open
    raise SerialException("could not open port %s: %s" % (self._port, msg))
serial.serialutil.SerialException: could not open port /dev/ttyAMA0: [Errno 13] Permission denied: '/dev/ttyAMA0'

**Comment by jcroucher** [comment]
> serial.serialutil.SerialException: could not open port /dev/ttyAMA0: [Errno 13] Permission denied: '/dev/ttyAMA0'

Try run as sudo or change the permissions on /dev/ttyAMA0

**Comment by praveenmalav09** [comment]
I didn't get 'ttyAMA0' file in /dev what can I do to get this file?

**Comment by jcroucher** [comment]
/dev/ttyAMA0 is not a file as such, it's the actual device.
It could be coming up as something else or your connections are incorrect.

**Comment by praveenmalav09** [comment]
and how to set up the serial port for 57600 baud and AMA0 while i doesn't have /dev/ttyAMA0 file...

**Comment by praveenmalav09** [comment]
can you please tell me which pin of R305 connect to which GPIO pin of Pi3.

**Comment by jcroucher** [comment]
> can you please tell me which pin of R305 connect to which GPIO pin of Pi3.

https://github.com/duste/FingerprintScannerRaspberryPi/issues/1#issuecomment-234529652

**Comment by praveenmalav09** [comment]
thanks it is working.

**Comment by praveenmalav09** [comment]
Can you please tell me how can i create and manage database for fingerprint
Sensor R305 using raspberry pi 3?
