### ISSUE TITLE
Serial port is open.

### ISSUE THREAD

**Issue by praveenmalav09** [duste/FingerprintScannerRaspberryPi#3]
How can i remove this error.

Serial port setup on /dev/ttyAMA0
Serial port is open
Traceback (most recent call last):
  File "FPRunTest.py", line 392, in <module>
    main()
  File "FPRunTest.py", line 328, in main
    if(Fingerprint.checkFPComms()):
  File "/home/pi/FP/Fingerprint.py", line 421, in checkFPComms
    rxLength = rxPacket[8] - 2
TypeError: unsupported operand type(s) for -: 'str' and 'int'

**Comment by jcroucher** [comment]
I note that on the line above it was converting the string to the unicode value, but has been commented out and replaced.

#rxLength = (ord(rxPacket[8])) - 2
rxLength = rxPacket[8] - 2

Try swapping back to the previous version.

https://docs.python.org/2/library/functions.html#ord

**Comment by praveenmalav09** [comment]
Okay, now it is working.
Now I want to know that how can we store valid Fingerprint id and Fingerprint in a file.

**Comment by jcroucher** [comment]
The fingerprint is stored in the scanner itself. 
You first have to store the fingerprint using a registration process. This will store a fingerprint against a specified ID on the device. 
Then when you do a scan event, it will return an ID or not found, in the response.

**Comment by duste** [comment]
If you fallow the process in FPRunTest.py imageUpload() line 190, it will pull the image from the sensor to the RPi.  It pulls the scanned image and assigns an ID, but it is not registered.  To register the fingerprint, I scanned the image to file then uploaded it back into the scanner and used it for the first and second scan.
