### ISSUE TITLE
To connect LCD

### ISSUE THREAD

**Issue by praveenmalav09** [duste/FingerprintScannerRaspberryPi#4]
How to connect 16*2 LCD to raspberry pi 3?

**Comment by jcroucher** [comment]
This appears to be off-topic. I recommend finding a support forum for the screen you have purchased.
However, you usually connect screens up using either HDMI or the DSI ribbon connector.

**Comment by duste** [comment]
some are I2C and some are serial.  You need to check the data sheet for that LCD screen.
