### ISSUE TITLE
Using with Raspberry PI 2

### ISSUE THREAD

**Issue by hugohomesquita** [duste/FingerprintScannerRaspberryPi#5]
I am trying to use with raspberry pi 2 and any command the reader light turns on and it immediately shuts off. Can you tell me why?

**Comment by duste** [comment]
You need to put it into a loop to look for a fingerprint.  It will only read a fingerprint if you are telling it to look for one.

**Comment by praveenmalav09** [comment]
Can you please tell me how can i create and manage database for fingerprint Sensor R305 using raspberry pi 3?
