### ISSUE TITLE
Receive packet error - Rx'd:1

### ISSUE THREAD

**Issue by ardawan** [duste/FingerprintScannerRaspberryPi#8]
on the RPI [3 model b+], fingerprint [ZFM-60],  i've followed the instructions and tried many ways but i get no result.
What am i doing wrong?

- removed console=xxx from /boot/cmdline.txt
- set enable_uart=1 in /boot/config.txt
- reboot
- connect the fingerprint through USB to the RPI
- ls /dev/
  - i found ttyUSB0 & serial(this is a directory) when i connect the fingerprint to the RPI. the rest of the list will be the same even if i disconnect the fingerprint from the USB port
- connect the fingerprint to the USB

*Even i tried to connect the RX and TX wires on the GPIO (BCM14, BCM15). will get the same result*
- *Green TD fingerprint sensor-> RX GPIO BCM15*
- *White RD fingerprint sensor -> TX GPIO BCM14*
- *changed inputPinExit to 10(BCM15)[RX] in FPRunTest.py*
- *changed outputPin to 8(BCM14)[TX] in FPRunTest.py*

**first try**
- edit usbport = '/dev/ttyUSB0' on Fingerprint.py
```
sudo python3 FPRunTest.py
```
result
```
Serial port setup on /dev/ttyUSB0
Serial port is open
Receive packet error - Rx'd:1
Did not find Fingerprint Sensor
```

**second try**
- edit usbport = '/dev/ttyS0' on Fingerprint.py
```
sudo python3 FPRunTest.py
```
result
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 312, in _reconfigure_port
    orig_attr = termios.tcgetattr(self.fd)
termios.error: (5, 'Input/output error')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "FPRunTest.py", line 393, in <module>
    main()
  File "FPRunTest.py", line 327, in main
    Fingerprint.begin()
  File "/home/pi/Desktop/FP/Fingerprint.py", line 44, in begin
    rtscts)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 236, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 272, in open
    self._reconfigure_port(force_update=True)
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 315, in _reconfigure_port
    raise SerialException("Could not configure port: {}".format(msg))
serial.serialutil.SerialException: Could not configure port: (5, 'Input/output error')
```

**third try**
-edit usbport = '/dev/serial0' on Fingerprint.py
```
sudo python3 FPRunTest.py
```
result
```
Serial port setup on /dev/serial0
Serial port is open
Receive packet error - Rx'd:1
Did not find Fingerprint Sensor
```

**Comment by duste** [comment]
Your using pi3. I wrote this for original B+. I will look into what the differences are.

**Comment by ardawan** [comment]
Yes I’m using pi 3 model B+. I even tested my UART to communicate via minicom program and seems everything is okay on my UART ports.

**Comment by ardawan** [comment]
> Your using pi3. I wrote this for original B+. I will look into what the differences are.

When i play around with the RPI settings such as /boot/config.txt & /boot/cmdline.txt, now im getting new Error while the sensor connected directly to the UART pins(bcm14,15) and usbport = '/dev/ttyS0' in Fingerprint.py

```
$ python3 FPRunTest.py 
Serial port setup on /dev/ttyS0
Serial port is open
Receive packet error - Rx'd:6
Did not find Fingerprint Sensor
```

**Comment by ardawan** [comment]
> > Your using pi3. I wrote this for original B+. I will look into what the differences are.
> 
> When i play around with the RPI settings such as /boot/config.txt & /boot/cmdline.txt, now im getting new Error while the sensor connected directly to the UART pins(bcm14,15) and usbport = '/dev/ttyS0' in Fingerprint.py
> 
> ```
> $ python3 FPRunTest.py 
> Serial port setup on /dev/ttyS0
> Serial port is open
> Receive packet error - Rx'd:6
> Did not find Fingerprint Sensor
> ```

also another error i get, when i change the baudrate from the Fingerprint.py to 115200, i will get different error number.
```
Receive packet error - Rx'd:9
```
